<?php

namespace WallBundle\Repository;

/**
 * wallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class wallRepository extends \Doctrine\ORM\EntityRepository
{
}
